# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dial.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 568)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dial = QtWidgets.QDial(self.centralwidget)
        # Set Dial Defaults
        # self.dial.setMinimum(10)
        # self.dial.setMaximum(360)
        self.dial.setRange(100, 200)
        # Set default start pos
        self.dial.setValue(150)
        # Use Dial
        self.dial.valueChanged.connect(self.dialer)
        # Set notches
        self.dial.setNotchesVisible(True)
        # Set color
        self.dial.setStyleSheet('background-color: #377235;')
        self.dial.setGeometry(QtCore.QRect(240, 50, 241, 211))
        self.dial.setObjectName("dial")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 330, 451, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 760, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dial"))
        self.label.setText(_translate("MainWindow", "Current Position: 0"))
    
    def dialer(self):
        # Grab the current dial pos
        value = self.dial.value()
        self.label.setText(f'Current position: {value}')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
