# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sixth_lesson.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.hello_world_label = QtWidgets.QLabel(self.centralwidget)
        self.hello_world_label.setGeometry(QtCore.QRect(6, 2, 781, 281))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.hello_world_label.setFont(font)
        self.hello_world_label.setAlignment(QtCore.Qt.AlignCenter)
        self.hello_world_label.setObjectName("hello_world_label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget, clicked=self.press_it)
        self.pushButton.setGeometry(QtCore.QRect(70, 280, 661, 251))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # Press the button func
    def press_it(self):
        self.hello_world_label.setText('BOOM!')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.hello_world_label.setText(_translate("MainWindow", "Hello World!"))
        self.pushButton.setText(_translate("MainWindow", "CLick Me!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
