# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'to_do.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(620, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.add_button = QtWidgets.QPushButton(self.centralwidget, clicked=self.add_it)
        self.add_button.setGeometry(QtCore.QRect(20, 72, 180, 26))
        self.add_button.setObjectName("add_button")
        self.delete_button = QtWidgets.QPushButton(self.centralwidget, clicked=self.delete_it)
        self.delete_button.setGeometry(QtCore.QRect(220, 72, 180, 26))
        self.delete_button.setObjectName("delete_button")
        self.clear_button = QtWidgets.QPushButton(self.centralwidget, clicked=self.clear_it)
        self.clear_button.setGeometry(QtCore.QRect(420, 72, 180, 26))
        self.clear_button.setObjectName("clear_button")
        self.line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.line_edit.setGeometry(QtCore.QRect(20, 20, 580, 41))
        self.line_edit.setObjectName("line_edit")
        self.list_widget = QtWidgets.QListWidget(self.centralwidget)
        self.list_widget.setGeometry(QtCore.QRect(20, 110, 580, 331))
        self.list_widget.setObjectName("list_widget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 620, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    # Add item to list
    def add_it(self):
        if self.line_edit.text() != '':
            item = self.line_edit.text()
            self.line_edit.setText('')
            self.list_widget.addItem(item)
    
    # Delete item from list
    def delete_it(self):
        # Grab the selected row
        clicked = self.list_widget.currentRow()
        # if clicked != -1:
        self.list_widget.takeItem(clicked)


    # Clear all items from list
    def clear_it(self):
        self.list_widget.clear()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "To Fo List"))
        self.add_button.setText(_translate("MainWindow", "Add Item To List"))
        self.delete_button.setText(_translate("MainWindow", "Delete Item From List"))
        self.clear_button.setText(_translate("MainWindow", "Clear The List"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
